// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: audit.proto

package auditv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Actor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Department    string                 `protobuf:"bytes,4,opt,name=department,proto3" json:"department,omitempty"`
	Roles         []string               `protobuf:"bytes,5,rep,name=roles,proto3" json:"roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Actor) Reset() {
	*x = Actor{}
	mi := &file_audit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Actor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Actor) ProtoMessage() {}

func (x *Actor) ProtoReflect() protoreflect.Message {
	mi := &file_audit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Actor.ProtoReflect.Descriptor instead.
func (*Actor) Descriptor() ([]byte, []int) {
	return file_audit_proto_rawDescGZIP(), []int{0}
}

func (x *Actor) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Actor) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Actor) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Actor) GetDepartment() string {
	if x != nil {
		return x.Department
	}
	return ""
}

func (x *Actor) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

type Target struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Target) Reset() {
	*x = Target{}
	mi := &file_audit_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Target) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Target) ProtoMessage() {}

func (x *Target) ProtoReflect() protoreflect.Message {
	mi := &file_audit_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Target.ProtoReflect.Descriptor instead.
func (*Target) Descriptor() ([]byte, []int) {
	return file_audit_proto_rawDescGZIP(), []int{1}
}

func (x *Target) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Target) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Target) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type FieldChange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	BeforeJson    string                 `protobuf:"bytes,2,opt,name=before_json,json=beforeJson,proto3" json:"before_json,omitempty"`
	AfterJson     string                 `protobuf:"bytes,3,opt,name=after_json,json=afterJson,proto3" json:"after_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldChange) Reset() {
	*x = FieldChange{}
	mi := &file_audit_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldChange) ProtoMessage() {}

func (x *FieldChange) ProtoReflect() protoreflect.Message {
	mi := &file_audit_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldChange.ProtoReflect.Descriptor instead.
func (*FieldChange) Descriptor() ([]byte, []int) {
	return file_audit_proto_rawDescGZIP(), []int{2}
}

func (x *FieldChange) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *FieldChange) GetBeforeJson() string {
	if x != nil {
		return x.BeforeJson
	}
	return ""
}

func (x *FieldChange) GetAfterJson() string {
	if x != nil {
		return x.AfterJson
	}
	return ""
}

type EventEnvelope struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	EventId string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	// The server authorizes this value against the signed OAuth client_id (or
	// compatible azp). The subject claim is never treated as client identity.
	SourceSystem       string                 `protobuf:"bytes,2,opt,name=source_system,json=sourceSystem,proto3" json:"source_system,omitempty"`
	EventType          string                 `protobuf:"bytes,3,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	SchemaId           string                 `protobuf:"bytes,4,opt,name=schema_id,json=schemaId,proto3" json:"schema_id,omitempty"`
	SchemaVersion      int32                  `protobuf:"varint,5,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	OccurredAt         *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	OperationId        string                 `protobuf:"bytes,7,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	CausationId        string                 `protobuf:"bytes,8,opt,name=causation_id,json=causationId,proto3" json:"causation_id,omitempty"`
	CorrelationId      string                 `protobuf:"bytes,9,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	TraceId            string                 `protobuf:"bytes,10,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	SpanId             string                 `protobuf:"bytes,11,opt,name=span_id,json=spanId,proto3" json:"span_id,omitempty"`
	Actor              *Actor                 `protobuf:"bytes,12,opt,name=actor,proto3" json:"actor,omitempty"`
	Targets            []*Target              `protobuf:"bytes,13,rep,name=targets,proto3" json:"targets,omitempty"`
	AggregateType      string                 `protobuf:"bytes,14,opt,name=aggregate_type,json=aggregateType,proto3" json:"aggregate_type,omitempty"`
	AggregateId        string                 `protobuf:"bytes,15,opt,name=aggregate_id,json=aggregateId,proto3" json:"aggregate_id,omitempty"`
	AggregateVersion   int64                  `protobuf:"varint,16,opt,name=aggregate_version,json=aggregateVersion,proto3" json:"aggregate_version,omitempty"`
	Action             string                 `protobuf:"bytes,17,opt,name=action,proto3" json:"action,omitempty"`
	Outcome            string                 `protobuf:"bytes,18,opt,name=outcome,proto3" json:"outcome,omitempty"`
	Reason             string                 `protobuf:"bytes,19,opt,name=reason,proto3" json:"reason,omitempty"`
	ChangedFields      []*FieldChange         `protobuf:"bytes,20,rep,name=changed_fields,json=changedFields,proto3" json:"changed_fields,omitempty"`
	PayloadJson        []byte                 `protobuf:"bytes,21,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"`
	PayloadRef         string                 `protobuf:"bytes,22,opt,name=payload_ref,json=payloadRef,proto3" json:"payload_ref,omitempty"`
	DataClassification string                 `protobuf:"bytes,23,opt,name=data_classification,json=dataClassification,proto3" json:"data_classification,omitempty"`
	RetentionClass     string                 `protobuf:"bytes,24,opt,name=retention_class,json=retentionClass,proto3" json:"retention_class,omitempty"`
	IdempotencyKey     string                 `protobuf:"bytes,25,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	WorkflowInstanceId string                 `protobuf:"bytes,26,opt,name=workflow_instance_id,json=workflowInstanceId,proto3" json:"workflow_instance_id,omitempty"`
	ExecutionRunId     string                 `protobuf:"bytes,27,opt,name=execution_run_id,json=executionRunId,proto3" json:"execution_run_id,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *EventEnvelope) Reset() {
	*x = EventEnvelope{}
	mi := &file_audit_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventEnvelope) ProtoMessage() {}

func (x *EventEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_audit_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventEnvelope.ProtoReflect.Descriptor instead.
func (*EventEnvelope) Descriptor() ([]byte, []int) {
	return file_audit_proto_rawDescGZIP(), []int{3}
}

func (x *EventEnvelope) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *EventEnvelope) GetSourceSystem() string {
	if x != nil {
		return x.SourceSystem
	}
	return ""
}

func (x *EventEnvelope) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *EventEnvelope) GetSchemaId() string {
	if x != nil {
		return x.SchemaId
	}
	return ""
}

func (x *EventEnvelope) GetSchemaVersion() int32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *EventEnvelope) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *EventEnvelope) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *EventEnvelope) GetCausationId() string {
	if x != nil {
		return x.CausationId
	}
	return ""
}

func (x *EventEnvelope) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *EventEnvelope) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *EventEnvelope) GetSpanId() string {
	if x != nil {
		return x.SpanId
	}
	return ""
}

func (x *EventEnvelope) GetActor() *Actor {
	if x != nil {
		return x.Actor
	}
	return nil
}

func (x *EventEnvelope) GetTargets() []*Target {
	if x != nil {
		return x.Targets
	}
	return nil
}

func (x *EventEnvelope) GetAggregateType() string {
	if x != nil {
		return x.AggregateType
	}
	return ""
}

func (x *EventEnvelope) GetAggregateId() string {
	if x != nil {
		return x.AggregateId
	}
	return ""
}

func (x *EventEnvelope) GetAggregateVersion() int64 {
	if x != nil {
		return x.AggregateVersion
	}
	return 0
}

func (x *EventEnvelope) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *EventEnvelope) GetOutcome() string {
	if x != nil {
		return x.Outcome
	}
	return ""
}

func (x *EventEnvelope) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *EventEnvelope) GetChangedFields() []*FieldChange {
	if x != nil {
		return x.ChangedFields
	}
	return nil
}

func (x *EventEnvelope) GetPayloadJson() []byte {
	if x != nil {
		return x.PayloadJson
	}
	return nil
}

func (x *EventEnvelope) GetPayloadRef() string {
	if x != nil {
		return x.PayloadRef
	}
	return ""
}

func (x *EventEnvelope) GetDataClassification() string {
	if x != nil {
		return x.DataClassification
	}
	return ""
}

func (x *EventEnvelope) GetRetentionClass() string {
	if x != nil {
		return x.RetentionClass
	}
	return ""
}

func (x *EventEnvelope) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *EventEnvelope) GetWorkflowInstanceId() string {
	if x != nil {
		return x.WorkflowInstanceId
	}
	return ""
}

func (x *EventEnvelope) GetExecutionRunId() string {
	if x != nil {
		return x.ExecutionRunId
	}
	return ""
}

type WriteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *EventEnvelope         `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	WaitFor       string                 `protobuf:"bytes,2,opt,name=wait_for,json=waitFor,proto3" json:"wait_for,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteRequest) Reset() {
	*x = WriteRequest{}
	mi := &file_audit_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteRequest) ProtoMessage() {}

func (x *WriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_audit_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteRequest.ProtoReflect.Descriptor instead.
func (*WriteRequest) Descriptor() ([]byte, []int) {
	return file_audit_proto_rawDescGZIP(), []int{4}
}

func (x *WriteRequest) GetEvent() *EventEnvelope {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *WriteRequest) GetWaitFor() string {
	if x != nil {
		return x.WaitFor
	}
	return ""
}

type WriteResponse struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	EventId  string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	TenantId string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Status   string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	// Read-only receipt field: the ledger stream is server-derived
	// (tenant + aggregate/operation/source) and stamped on ingest. The ingest
	// envelope (EventEnvelope) intentionally carries no stream_id — a
	// client-supplied value is stripped by Service.Ingest (stream
	// consistency), so any future envelope field must NOT be mapped.
	StreamId      string `protobuf:"bytes,4,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	Sequence      int64  `protobuf:"varint,5,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Hash          string `protobuf:"bytes,6,opt,name=hash,proto3" json:"hash,omitempty"`
	Duplicate     bool   `protobuf:"varint,7,opt,name=duplicate,proto3" json:"duplicate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteResponse) Reset() {
	*x = WriteResponse{}
	mi := &file_audit_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteResponse) ProtoMessage() {}

func (x *WriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_audit_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteResponse.ProtoReflect.Descriptor instead.
func (*WriteResponse) Descriptor() ([]byte, []int) {
	return file_audit_proto_rawDescGZIP(), []int{5}
}

func (x *WriteResponse) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *WriteResponse) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *WriteResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *WriteResponse) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *WriteResponse) GetSequence() int64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *WriteResponse) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *WriteResponse) GetDuplicate() bool {
	if x != nil {
		return x.Duplicate
	}
	return false
}

type WriteBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*EventEnvelope       `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	WaitFor       string                 `protobuf:"bytes,2,opt,name=wait_for,json=waitFor,proto3" json:"wait_for,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteBatchRequest) Reset() {
	*x = WriteBatchRequest{}
	mi := &file_audit_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteBatchRequest) ProtoMessage() {}

func (x *WriteBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_audit_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteBatchRequest.ProtoReflect.Descriptor instead.
func (*WriteBatchRequest) Descriptor() ([]byte, []int) {
	return file_audit_proto_rawDescGZIP(), []int{6}
}

func (x *WriteBatchRequest) GetEvents() []*EventEnvelope {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *WriteBatchRequest) GetWaitFor() string {
	if x != nil {
		return x.WaitFor
	}
	return ""
}

type WriteBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Receipts      []*WriteResponse       `protobuf:"bytes,1,rep,name=receipts,proto3" json:"receipts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteBatchResponse) Reset() {
	*x = WriteBatchResponse{}
	mi := &file_audit_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteBatchResponse) ProtoMessage() {}

func (x *WriteBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_audit_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteBatchResponse.ProtoReflect.Descriptor instead.
func (*WriteBatchResponse) Descriptor() ([]byte, []int) {
	return file_audit_proto_rawDescGZIP(), []int{7}
}

func (x *WriteBatchResponse) GetReceipts() []*WriteResponse {
	if x != nil {
		return x.Receipts
	}
	return nil
}

var File_audit_proto protoreflect.FileDescriptor

const file_audit_proto_rawDesc = "" +
	"\n" +
	"\vaudit.proto\x12\x11snaplink.audit.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"u\n" +
	"\x05Actor\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1e\n" +
	"\n" +
	"department\x18\x04 \x01(\tR\n" +
	"department\x12\x14\n" +
	"\x05roles\x18\x05 \x03(\tR\x05roles\"@\n" +
	"\x06Target\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"c\n" +
	"\vFieldChange\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12\x1f\n" +
	"\vbefore_json\x18\x02 \x01(\tR\n" +
	"beforeJson\x12\x1d\n" +
	"\n" +
	"after_json\x18\x03 \x01(\tR\tafterJson\"\xa0\b\n" +
	"\rEventEnvelope\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12#\n" +
	"\rsource_system\x18\x02 \x01(\tR\fsourceSystem\x12\x1d\n" +
	"\n" +
	"event_type\x18\x03 \x01(\tR\teventType\x12\x1b\n" +
	"\tschema_id\x18\x04 \x01(\tR\bschemaId\x12%\n" +
	"\x0eschema_version\x18\x05 \x01(\x05R\rschemaVersion\x12;\n" +
	"\voccurred_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\x12!\n" +
	"\foperation_id\x18\a \x01(\tR\voperationId\x12!\n" +
	"\fcausation_id\x18\b \x01(\tR\vcausationId\x12%\n" +
	"\x0ecorrelation_id\x18\t \x01(\tR\rcorrelationId\x12\x19\n" +
	"\btrace_id\x18\n" +
	" \x01(\tR\atraceId\x12\x17\n" +
	"\aspan_id\x18\v \x01(\tR\x06spanId\x12.\n" +
	"\x05actor\x18\f \x01(\v2\x18.snaplink.audit.v1.ActorR\x05actor\x123\n" +
	"\atargets\x18\r \x03(\v2\x19.snaplink.audit.v1.TargetR\atargets\x12%\n" +
	"\x0eaggregate_type\x18\x0e \x01(\tR\raggregateType\x12!\n" +
	"\faggregate_id\x18\x0f \x01(\tR\vaggregateId\x12+\n" +
	"\x11aggregate_version\x18\x10 \x01(\x03R\x10aggregateVersion\x12\x16\n" +
	"\x06action\x18\x11 \x01(\tR\x06action\x12\x18\n" +
	"\aoutcome\x18\x12 \x01(\tR\aoutcome\x12\x16\n" +
	"\x06reason\x18\x13 \x01(\tR\x06reason\x12E\n" +
	"\x0echanged_fields\x18\x14 \x03(\v2\x1e.snaplink.audit.v1.FieldChangeR\rchangedFields\x12!\n" +
	"\fpayload_json\x18\x15 \x01(\fR\vpayloadJson\x12\x1f\n" +
	"\vpayload_ref\x18\x16 \x01(\tR\n" +
	"payloadRef\x12/\n" +
	"\x13data_classification\x18\x17 \x01(\tR\x12dataClassification\x12'\n" +
	"\x0fretention_class\x18\x18 \x01(\tR\x0eretentionClass\x12'\n" +
	"\x0fidempotency_key\x18\x19 \x01(\tR\x0eidempotencyKey\x120\n" +
	"\x14workflow_instance_id\x18\x1a \x01(\tR\x12workflowInstanceId\x12(\n" +
	"\x10execution_run_id\x18\x1b \x01(\tR\x0eexecutionRunId\"a\n" +
	"\fWriteRequest\x126\n" +
	"\x05event\x18\x01 \x01(\v2 .snaplink.audit.v1.EventEnvelopeR\x05event\x12\x19\n" +
	"\bwait_for\x18\x02 \x01(\tR\awaitFor\"\xca\x01\n" +
	"\rWriteResponse\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1b\n" +
	"\tstream_id\x18\x04 \x01(\tR\bstreamId\x12\x1a\n" +
	"\bsequence\x18\x05 \x01(\x03R\bsequence\x12\x12\n" +
	"\x04hash\x18\x06 \x01(\tR\x04hash\x12\x1c\n" +
	"\tduplicate\x18\a \x01(\bR\tduplicate\"h\n" +
	"\x11WriteBatchRequest\x128\n" +
	"\x06events\x18\x01 \x03(\v2 .snaplink.audit.v1.EventEnvelopeR\x06events\x12\x19\n" +
	"\bwait_for\x18\x02 \x01(\tR\awaitFor\"R\n" +
	"\x12WriteBatchResponse\x12<\n" +
	"\breceipts\x18\x01 \x03(\v2 .snaplink.audit.v1.WriteResponseR\breceipts2\x85\x02\n" +
	"\x06Ingest\x12J\n" +
	"\x05Write\x12\x1f.snaplink.audit.v1.WriteRequest\x1a .snaplink.audit.v1.WriteResponse\x12Y\n" +
	"\n" +
	"WriteBatch\x12$.snaplink.audit.v1.WriteBatchRequest\x1a%.snaplink.audit.v1.WriteBatchResponse\x12T\n" +
	"\vWriteStream\x12\x1f.snaplink.audit.v1.WriteRequest\x1a .snaplink.audit.v1.WriteResponse(\x010\x01B8Z6github.com/snaplink/audit-governance/api/proto;auditv1b\x06proto3"

var (
	file_audit_proto_rawDescOnce sync.Once
	file_audit_proto_rawDescData []byte
)

func file_audit_proto_rawDescGZIP() []byte {
	file_audit_proto_rawDescOnce.Do(func() {
		file_audit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_audit_proto_rawDesc), len(file_audit_proto_rawDesc)))
	})
	return file_audit_proto_rawDescData
}

var file_audit_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_audit_proto_goTypes = []any{
	(*Actor)(nil),                 // 0: snaplink.audit.v1.Actor
	(*Target)(nil),                // 1: snaplink.audit.v1.Target
	(*FieldChange)(nil),           // 2: snaplink.audit.v1.FieldChange
	(*EventEnvelope)(nil),         // 3: snaplink.audit.v1.EventEnvelope
	(*WriteRequest)(nil),          // 4: snaplink.audit.v1.WriteRequest
	(*WriteResponse)(nil),         // 5: snaplink.audit.v1.WriteResponse
	(*WriteBatchRequest)(nil),     // 6: snaplink.audit.v1.WriteBatchRequest
	(*WriteBatchResponse)(nil),    // 7: snaplink.audit.v1.WriteBatchResponse
	(*timestamppb.Timestamp)(nil), // 8: google.protobuf.Timestamp
}
var file_audit_proto_depIdxs = []int32{
	8,  // 0: snaplink.audit.v1.EventEnvelope.occurred_at:type_name -> google.protobuf.Timestamp
	0,  // 1: snaplink.audit.v1.EventEnvelope.actor:type_name -> snaplink.audit.v1.Actor
	1,  // 2: snaplink.audit.v1.EventEnvelope.targets:type_name -> snaplink.audit.v1.Target
	2,  // 3: snaplink.audit.v1.EventEnvelope.changed_fields:type_name -> snaplink.audit.v1.FieldChange
	3,  // 4: snaplink.audit.v1.WriteRequest.event:type_name -> snaplink.audit.v1.EventEnvelope
	3,  // 5: snaplink.audit.v1.WriteBatchRequest.events:type_name -> snaplink.audit.v1.EventEnvelope
	5,  // 6: snaplink.audit.v1.WriteBatchResponse.receipts:type_name -> snaplink.audit.v1.WriteResponse
	4,  // 7: snaplink.audit.v1.Ingest.Write:input_type -> snaplink.audit.v1.WriteRequest
	6,  // 8: snaplink.audit.v1.Ingest.WriteBatch:input_type -> snaplink.audit.v1.WriteBatchRequest
	4,  // 9: snaplink.audit.v1.Ingest.WriteStream:input_type -> snaplink.audit.v1.WriteRequest
	5,  // 10: snaplink.audit.v1.Ingest.Write:output_type -> snaplink.audit.v1.WriteResponse
	7,  // 11: snaplink.audit.v1.Ingest.WriteBatch:output_type -> snaplink.audit.v1.WriteBatchResponse
	5,  // 12: snaplink.audit.v1.Ingest.WriteStream:output_type -> snaplink.audit.v1.WriteResponse
	10, // [10:13] is the sub-list for method output_type
	7,  // [7:10] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_audit_proto_init() }
func file_audit_proto_init() {
	if File_audit_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_audit_proto_rawDesc), len(file_audit_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_audit_proto_goTypes,
		DependencyIndexes: file_audit_proto_depIdxs,
		MessageInfos:      file_audit_proto_msgTypes,
	}.Build()
	File_audit_proto = out.File
	file_audit_proto_goTypes = nil
	file_audit_proto_depIdxs = nil
}
